### ISSUE TITLE
Write a File inside Android/data

### ISSUE THREAD

**Issue by adisiji** [Cheticamp/SAFWalker#1]
Hi,
Thanks it helped me for read file inside Android/data.
But do you have any idea to create a file inside Android/data? 
What I did:
```
        val uriData = DocumentsContract.buildDocumentUri(
            Constants.EXTERNAL_STORAGE_PROVIDER_AUTHORITY,
            "${Constants.ANDROID_DOCID}/data"
        )
        val docDataFile = DocumentFile.fromSingleUri(context, uriData)
        val docFile = DocumentsContract.createDocument(contentResolver, uriData, mime, fileName)
```
It gives error when I invoke `DocumentsContract.createDocument` :
`Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/primary%3AAndroid%2Fdata from pid=9396, uid=10154 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()` 

Thanks in Advance !

**Comment by Cheticamp** [comment]
I haven't looked at writing file in that folder but only looked at reading them. This is a short-term thing anyway that will be patched shortly. See [here](https://issuetracker.google.com/issues/178910699#comment13).
